name: Manual Build dev-php-fpm Docker

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: latest
    env:
      BUILDKIT_PROGRESS: plain   # show detailed Docker build logs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push dev-php-fpm Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./docker/library/dockers/dev-php-fpm
          tags: anish443/dev-php-fpm:pre-build-dev-85
          platforms: linux/amd64
          push: true
          no-cache: true
